jpom:
  # jpom 数据存储路径, 如果调试模式运行默认路径为【${user.home}/jpom/】,安装运行默认为jar包文件的父级
  path:
  authorize:
    # api接口请求token 长度要求大于等于6位，字母数字符号组合
    token:
    #登录token失效时间(单位：小时),默认为24
    expired: 24
    #登录token失效后自动续签时间（单位：分钟），默认为60，不自动续签
    renewal: 60
    # jwt 签名(加密)的key 长度建议控制到 16位
    key:
  # 前端接口 超时时间 单位秒
  webApiTimeout: 20
  # 系统名称
  name:
  # 副标题
  subTitle:
  # 登录页名称
  loginTitle:
  # logo 文件路径（绝对路径、http） jpg、png、gif、
  logoFile:
  # 禁用页面引导导航
  disabledGuide: false
  # 禁用登录图形验证码 （一般用于服务器没有字体或者开启了两部验证后才关闭图形验证码）
  disabledCaptcha: false
user:
  # 最多能创建多少个用户
  maxCount: 10
  # 用户连续登录失败次数，超过此数将被限制登录
  alwaysLoginError: 5
  # 当ip连续登录失败，锁定对应IP时长，单位毫秒
  ipErrorLockTime: 60*60*5*1000
consoleLog:
  # 是否记录接口请求日志
  reqXss: true
  # 是否记录接口响应日志
  reqResponse: true
  # 控制台编码格式
  charset:
log:
  # 日志文件的编码格式，如果没有指定就自动识别，自动识别可能出现不准确的情况
  fileCharset:
  # 查看日志时初始读取最后多少行（默认10，0不读取）
  intiReadLine: 10
db:
  # 日志存储条数，将自动清理旧数据,配置小于等于零则不清理
  logStorageCount: 10000
  # 数据库账号 默认 jpom
  userName: jpom
  # 数据库密码 默认 jpom 如果自行配置请保证密码强度
  userPwd: jpom
  # h2 数据库缓存大小  kilobyte 1KB 1,024 megabyte 1MB 1,048,576
  cacheSize:
  # 自动备份间隔天数 小于等于 0 不自动备份
  autoBackupIntervalDay: 1
  # 自动备份保留天数 小于等于 0，不自动删除自动备份数据
  autoBackupReserveDay: 5
# spring 相关配置
spring:
  h2:
    console:
      # 是否开启 web 访问数据库（url: http://${ip}:${port}/h2-console）
      enabled: false
      # 是否允许远程访问（开启此配置有安全风险），默认为 false（当部署到服务器上之后，是否可以通过其他浏览器访问数据库）
      settings:
        web-allow-others: false
# 构建相关配置
build:
  # 最多保存多少份历史记录
  maxHistoryCount: 1000
  # 单个最多保存多少份历史记录
  itemMaxHistoryCount: 50
  # 构建命令是否检查 存在删除命令
  checkDeleteCommand: true
ssh:
  # ssh 执行命令的 默认加载的环境变量
  initEnv: source /etc/profile && source ~/.bash_profile && source ~/.bashrc
node:
  # 上传文件的超时时间 单位秒,最短5秒钟
  uploadFileTimeOut: 300
system:
  # cron 定时器是否开启匹配秒
  timerMatchSecond: false
  # 节点心跳监控时间 （需要大于零） 单位秒 最小配置 5秒
  nodeHeartSecond: 30
  # 旧包文件保留个数
  oldJarsCount: 2
  # Check the url for the new version
  remoteVersionUrl:
