name: codecov2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven cobertura
        run: mvn cobertura:cobertura -Pcobertura
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2